<div class="social-links">
    <div class="wrapper">
        <h3 class="title">Follow US</h3>
        <ul class="list">
            <li class="item"><a target="_blank" href="#" class="link social-link">
                    <svg class="svg-icon facebook-icon">
                        <use xlink:href="#facebook"></use>
                    </svg>
                </a>
            </li>
            <li class="item">
                <a target="_blank" href="#" class="link social-link">
                    <svg class="svg-icon -icon">
                        <use xlink:href="#twitter"></use>
                    </svg>
                </a>
            </li>
            <li class="item">
                <a target="_blank" href="#" class="link social-link">
                    <svg class="svg-icon -icon">
                        <use xlink:href="#pinterest"></use>
                    </svg>
                </a>
            </li>
            <li class="item">
                <a target="_blank" href="#" class="link social-link">
                    <svg class="svg-icon -icon">
                        <use xlink:href="#instagram"></use>
                    </svg>
                </a>
            </li>
        </ul>
    </div>
</div>
